const state={menu:[],areas:[],orders:[],area:'',table:null,cart:[],category:'all',choice:null,sending:false,screen:'tables'};
const $=(selector)=>document.querySelector(selector);
const esc=(value)=>String(value ?? '').replace(/[&<>'"]/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));
const money=(value)=>`₹${Number(value||0).toFixed(0)}`;
const requestId=()=>`captain-${Date.now()}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}`;
const itemKey=(line)=>`${line.name}::${line.category}::${line.portion}::${line.style}`;
function priceOptions(item){return [['Half',item.halfPrice],['Full',item.fullPrice],['With bone',item.withBonePrice],['Boneless',item.bonelessPrice],['30 ml',item.price30ml],['60 ml',item.price60ml],['90 ml',item.price90ml],['180 ml',item.price180ml],['Regular',item.price]].map(([portion,value])=>[portion,Number(String(value||'').replace(/[^0-9.]/g,''))||0]).filter(([,value])=>value>0);}
function total(){return state.cart.reduce((sum,line)=>sum+line.quantity*(line.price+(line.style?10:0)),0)}
function itemCount(){return state.cart.reduce((sum,line)=>sum+line.quantity,0)}
function activeTable(area,number){return state.orders.find((order)=>order.mode==='table'&&String(order.table_area)===String(area)&&Number(order.table_number)===Number(number)&&!['completed','rejected','cancelled'].includes(order.status));}
function setScreen(screen){state.screen=screen;['tables','menu','review'].forEach((name)=>$(`#${name}-screen`).hidden=name!==screen);$('#basket-bar').hidden=screen==='tables'||!state.cart.length;if(screen==='menu')$('#menu-table-title').textContent=`Order for ${state.table.area} · Table ${String(state.table.number).padStart(2,'0')}`;if(screen==='review'){$('#review-table-title').textContent=`Table ${String(state.table.number).padStart(2,'0')} · ${state.table.area}`;renderCart();}window.scrollTo({top:0,behavior:'instant'});}
function renderTables(){const tabs=$('#area-tabs');if(!state.areas.length){tabs.innerHTML='';$('#table-board').innerHTML='<p class="cart-empty">No table areas are configured. Ask a manager to configure them in Orders → Operations.</p>';return;}if(!state.areas.some((area)=>area.name===state.area))state.area=state.areas[0].name;tabs.innerHTML=[['all','All tables'],...state.areas.map((area)=>[area.name,area.name])].map(([id,label])=>`<button class="area-tab${state.area===id?' is-active':''}" data-area="${esc(id)}" type="button">${esc(label)}</button>`).join('');const areas=state.area==='all'?state.areas:state.areas.filter((area)=>area.name===state.area);const cards=areas.flatMap((area)=>Array.from({length:Number(area.to)-Number(area.from)+1},(_,index)=>({area:area.name,number:Number(area.from)+index})));$('#table-board').innerHTML=cards.map(({area,number})=>{const active=activeTable(area,number),selected=state.table?.area===area&&state.table?.number===number;return `<button type="button" class="table-tile${active?' is-active':''}${selected?' is-selected':''}" data-table-area="${esc(area)}" data-table-number="${number}" ${active?'disabled title="This table is active in the billing console"':''}><span>${esc(area)}</span><b>${String(number).padStart(2,'0')}</b><small>${active?`${String(active.status||'active').replace(/^./,(letter)=>letter.toUpperCase())} · Active`:'Available'}</small></button>`}).join('');}
function renderMenu(){const query=$('#menu-search').value.trim().toLowerCase(),available=state.menu.filter((item)=>!item.unavailable),categories=[...new Set(available.map((item)=>item.category||'Menu'))].sort();if(!categories.includes(state.category)&&state.category!=='all')state.category='all';$('#category-list').innerHTML=[['all','Best selling'],...categories.map((category)=>[category,category])].map(([key,label])=>`<button class="category${state.category===key?' is-active':''}" type="button" data-category="${esc(key)}">${esc(label)}</button>`).join('');const visible=available.filter((item)=>(state.category==='all'||item.category===state.category)&&`${item.name} ${item.category}`.toLowerCase().includes(query));$('#menu-list').innerHTML=visible.length?visible.map((item)=>{const options=priceOptions(item),first=options[0]||['',0],dietary=/\b(chicken|fish|prawn|meat|egg|mutton|beef|pork)\b/i.test(`${item.name} ${item.category}`)?'nonveg':'veg';return `<button type="button" class="menu-item" data-menu-index="${state.menu.indexOf(item)}"><i class="diet ${dietary}" aria-label="${dietary==='veg'?'Vegetarian':'Non-vegetarian'}"></i><span>${esc(item.category||'Menu')}</span><b>${esc(item.name)}</b><small>${options.length>1?'From ':''}${money(first[1])}${options.length>1?' · choose':''}</small></button>`}).join(''):'<p class="cart-empty">No available dishes match your search.</p>';}
function renderCart(){const root=$('#cart-list'),count=itemCount(),amount=total();root.innerHTML=state.cart.length?state.cart.map((line,index)=>`<article class="cart-line"><span><b>${esc(line.name)}${line.portion?` · ${esc(line.portion)}`:''}${line.style?` · ${esc(line.style)}`:''}</b><small>${money(line.price)} each${line.style?' + ₹10 preparation':''}</small></span><div class="quantity"><button type="button" data-cart-change="-1" data-cart-index="${index}" aria-label="Remove one">−</button><b>${line.quantity}</b><button type="button" data-cart-change="1" data-cart-index="${index}" aria-label="Add one">+</button></div><b>${money(line.quantity*(line.price+(line.style?10:0)))}</b></article>`).join(''):'<p class="cart-empty">No items yet. Go back and add dishes.</p>';$('#cart-caption').textContent=count?`${count} item${count===1?'':'s'} in this order.`:'No items in this order.';$('#review-total').textContent=money(amount);$('#cart-count').textContent=`${count} item${count===1?'':'s'}`;$('#basket-total').textContent=money(amount);$('#basket-bar').hidden=state.screen==='tables'||!count;$('#place-order').disabled=!count||state.sending||!navigator.onLine;$('#place-order').textContent=state.sending?'Sending order…':navigator.onLine?'Send to kitchen ↗':'Internet required';}
function openChoice(item){const options=priceOptions(item);if(!options.length)return;state.choice={item,option:options[0]};$('#choice-title').textContent=item.name;$('#choice-options').innerHTML=options.map(([portion,price],index)=>`<button type="button" class="choice-option${index===0?' is-selected':''}" data-choice-index="${index}"><b>${esc(portion)}</b><small>${money(price)}</small></button>`).join('');const style=$('#style-options');style.hidden=!item.gravyStyleAvailable;style.querySelector('input[value=""]').checked=true;$('#choice-sheet').showModal();}
function addChoice(){const choice=state.choice;if(!choice)return;const style=$('input[name="captain-style"]:checked')?.value||'',[portion,price]=choice.option,key=itemKey({name:choice.item.name,category:choice.item.category,portion,style});const existing=state.cart.find((line)=>line.key===key);if(existing)existing.quantity=Math.min(20,existing.quantity+1);else state.cart.push({key,name:choice.item.name,category:choice.item.category,portion,style,price,quantity:1});$('#choice-sheet').close();state.choice=null;renderCart();}
async function load(){try{$('#captain-connection').textContent='Loading live table status…';const [operations,menu,orders,availability]=await Promise.all([fetch('/api/orders/operations',{cache:'no-store'}),fetch('/api/orders/menu',{cache:'no-store'}),fetch('/api/orders?history=0',{cache:'no-store'}),fetch('/api/orders/availability',{cache:'no-store'})]);if(!operations.ok||!menu.ok||!orders.ok||!availability.ok)throw new Error('Unable to load Captain. Check your internet connection and sign in again.');const [operationData,menuData,orderData,availabilityData]=await Promise.all([operations.json(),menu.json(),orders.json(),availability.json()]);const unavailable=new Set(availabilityData.map((item)=>item.item_key));state.areas=Array.isArray(operationData.config?.tableAreas)?operationData.config.tableAreas:[];state.menu=(Array.isArray(menuData)?menuData:[]).map((item)=>({...item,unavailable:unavailable.has(item.key)}));state.orders=Array.isArray(orderData)?orderData:[];$('#captain-connection').textContent='Live table and menu status';renderTables();renderMenu();}catch(error){$('#captain-connection').textContent=error.message;}}
function clock(){const now=new Date();$('#captain-clock').textContent=new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',weekday:'short',hour:'2-digit',minute:'2-digit'}).format(now)}
$('#area-tabs').addEventListener('click',(event)=>{const button=event.target.closest('[data-area]');if(!button)return;state.area=button.dataset.area;renderTables();});
$('#table-board').addEventListener('click',(event)=>{const button=event.target.closest('[data-table-area]');if(!button||button.disabled)return;state.table={area:button.dataset.tableArea,number:Number(button.dataset.tableNumber)};state.cart=[];renderTables();renderCart();setScreen('menu');});
$('#category-list').addEventListener('click',(event)=>{const button=event.target.closest('[data-category]');if(!button)return;state.category=button.dataset.category;renderMenu();});
$('#menu-list').addEventListener('click',(event)=>{const button=event.target.closest('[data-menu-index]');const item=state.menu[Number(button?.dataset.menuIndex)];if(item)openChoice(item);});
$('#choice-options').addEventListener('click',(event)=>{const button=event.target.closest('[data-choice-index]');if(!button||!state.choice)return;state.choice.option=priceOptions(state.choice.item)[Number(button.dataset.choiceIndex)];[...$('#choice-options').querySelectorAll('.choice-option')].forEach((option)=>option.classList.toggle('is-selected',option===button));});
$('#choice-add').addEventListener('click',addChoice);$('#choice-close').addEventListener('click',()=>$('#choice-sheet').close());
$('#cart-list').addEventListener('click',(event)=>{const button=event.target.closest('[data-cart-index]');if(!button)return;const index=Number(button.dataset.cartIndex),line=state.cart[index];if(!line)return;line.quantity+=Number(button.dataset.cartChange);if(line.quantity<=0)state.cart.splice(index,1);renderCart();});
$('#menu-search').addEventListener('input',renderMenu);$('#menu-search-toggle').addEventListener('click',()=>{const wrap=$('#menu-search-wrap');wrap.hidden=!wrap.hidden;if(!wrap.hidden)$('#menu-search').focus();});$('#clear-menu-search').addEventListener('click',()=>{$('#menu-search').value='';renderMenu();});
document.querySelectorAll('[data-captain-back]').forEach((button)=>button.addEventListener('click',()=>setScreen(state.screen==='review'?'menu':'tables')));$('#basket-bar').addEventListener('click',()=>setScreen('review'));$('#refresh-captain').addEventListener('click',load);
$('#place-order').addEventListener('click',async()=>{if(state.sending||!state.table||!state.cart.length||!navigator.onLine)return;state.sending=true;renderCart();const status=$('#order-status');status.textContent='Saving your order…';const payload={clientRequestId:requestId(),source:'captain',action:'submit',tableArea:state.table.area,tableNumber:state.table.number,customerName:$('#customer-name').value.trim(),customerPhone:$('#customer-phone').value.trim(),specialRequest:$('#special-request').value.trim(),items:state.cart.map(({key,...item})=>item)};try{const response=await fetch('/api/orders/counter',{method:'POST',headers:{'Content-Type':'application/json','X-Counter-Order-Id':payload.clientRequestId},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Unable to save the order.');state.cart=[];state.table=null;$('#customer-name').value='';$('#customer-phone').value='';$('#special-request').value='';await load();setScreen('tables');$('#captain-connection').textContent=`Order #${data.orderNumber} sent to the billing console for kitchen routing.`;}catch(error){status.textContent=error.message||'Unable to send the order.';}finally{state.sending=false;renderCart();}});
window.addEventListener('online',()=>{load();renderCart();});window.addEventListener('offline',()=>{$('#captain-connection').textContent='Internet unavailable — Captain orders require a live connection.';renderCart();});
clock();setInterval(clock,30000);load();setInterval(()=>{if(navigator.onLine&&state.screen==='tables')load();},10000);
