const token = new URLSearchParams(location.search).get('token') || '';
const card = document.getElementById('tracking-card');
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' })[char]);
const label = (status) => ({ new:'Order received', accepted:'Accepted', preparing:'Preparing', ready:'Ready for collection', completed:'Completed', rejected:'Unable to accept', cancelled:'Cancelled' }[status] || 'Order received');
const render = (order) => { const status=String(order.status||'new'); const number=String(order.daily_order_number||'').padStart(2,'0'); const placed=new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'}).format(new Date(order.created_at)); const states=['accepted','preparing','ready']; const current=states.indexOf(status); const items=Array.isArray(order.items)?order.items:[]; const cancellation=status==='new'?`<button id="open-cancel" class="cancel-order">Cancel order</button><form id="cancel-form" class="cancel-form" hidden><label>Reason for cancellation<textarea id="cancel-reason" maxlength="240" placeholder="Please tell us why you need to cancel."></textarea></label><button type="submit">Confirm cancellation</button></form>`:status==='cancelled'?`<p class="cancelled-note">This order was cancelled${order.cancellation_reason?`: ${esc(order.cancellation_reason)}`:'.'}</p>`:''; card.innerHTML=`<p class="eyebrow">Red Lantern order</p><h1>Your order <span class="order-number">#${esc(number)}</span></h1><div class="status ${esc(status)}">${esc(label(status))}</div><div class="steps">${states.map((step,index)=>`<span class="step ${index<current?'ready':index===current?'active':''}">${esc(label(step))}</span>`).join('')}</div><p class="placed"><b>Placed:</b> ${esc(placed)} · Goa time</p><div class="items"><h2>Your items</h2>${items.map((item)=>`<div><b>${Number(item.quantity||0)}×</b> ${esc(item.name)}${item.portion?` (${esc(item.portion)})`:''}${item.style?` · ${esc(item.style)}`:''}</div>`).join('')}</div>${cancellation}`; };
async function load(){if(!/^[A-Za-z0-9_-]{24,128}$/.test(token)){card.innerHTML='<h1>Order link unavailable</h1><p class="muted">Please use the link from your order confirmation.</p>';return;}try{const response=await fetch(`/api/order-tracking/${encodeURIComponent(token)}`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error||'Order not found.');render(body);}catch(error){card.innerHTML=`<h1>We could not load this order</h1><p class="muted">${esc(error.message)}</p>`;}}
load();window.setInterval(load,15000);
card.addEventListener('click',(event)=>{if(event.target.id==='open-cancel'){document.getElementById('cancel-form').hidden=false;event.target.hidden=true;document.getElementById('cancel-reason').focus();}});
card.addEventListener('submit',async(event)=>{if(event.target.id!=='cancel-form')return;event.preventDefault();const button=event.target.querySelector('button');const reason=document.getElementById('cancel-reason').value.trim();if(reason.length<3){document.getElementById('cancel-reason').focus();return;}button.disabled=true;try{const response=await fetch(`/api/order-tracking/${encodeURIComponent(token)}/cancel`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Unable to cancel this order.');load();}catch(error){button.disabled=false;window.alert(error.message);}});
