const token = new URLSearchParams(location.search).get('token') || '';
const card = document.getElementById('tracking-card');
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' })[char]);
const trackingStatusStyles = document.createElement('style');
trackingStatusStyles.textContent = '.status-message{margin:-12px auto 20px;max-width:390px;color:#5e6e84;font-size:13px;line-height:1.5}.status-message.accepted{color:#1d5ebf}.status-message.preparing{color:#a16600}.status-message.ready{color:#087640;font-weight:800}.status-message.rejected{color:#a52a39}.status-message.completed{color:#43526a}';
document.head.appendChild(trackingStatusStyles);
const label = (status, fulfillmentType) => ({ new:'Order received', accepted:'Order accepted', preparing:'Preparing your order', ready:fulfillmentType === 'pickup' ? 'Ready for pickup' : 'Ready for delivery', completed:'Order completed', rejected:'Order rejected', cancelled:'Order cancelled' }[status] || 'Order received');
const statusMessage = (status, fulfillmentType) => ({ accepted:'Your order has been accepted. Our team will begin preparing it shortly.', preparing:'Our kitchen is preparing your order.', ready:fulfillmentType === 'pickup' ? 'Your order is ready for pickup.' : 'Your order is ready and will be sent for delivery.', completed:'Thank you — this order has been completed.', rejected:'We are unable to accept this order. Please contact the restaurant if you need help.' }[status] || 'We have received your order and will confirm it shortly.');
const render = (order) => { const status=String(order.status||'new'); const fulfillmentType=order.fulfillment_type === 'pickup' ? 'pickup' : 'delivery'; const number=String(order.daily_order_number||'').padStart(2,'0'); const placed=new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'}).format(new Date(order.created_at)); const states=['accepted','preparing','ready']; const current=states.indexOf(status); const items=Array.isArray(order.items)?order.items:[]; const cancellation=status==='new'?`<button id="open-cancel" class="cancel-order">Cancel order</button><form id="cancel-form" class="cancel-form" hidden><label>Reason for cancellation<textarea id="cancel-reason" maxlength="240" placeholder="Please tell us why you need to cancel."></textarea></label><button type="submit">Confirm cancellation</button></form>`:status==='cancelled'?`<p class="cancelled-note">This order was cancelled${order.cancellation_reason?`: ${esc(order.cancellation_reason)}`:'.'}</p>`:''; card.innerHTML=`<p class="eyebrow">Red Lantern order</p><h1>Your order <span class="order-number">#${esc(number)}</span></h1><div class="status ${esc(status)}">${esc(label(status, fulfillmentType))}</div><p class="status-message ${esc(status)}">${esc(statusMessage(status, fulfillmentType))}</p><div class="steps">${states.map((step,index)=>`<span class="step ${index<current?'ready':index===current?'active':''}">${esc(label(step, fulfillmentType))}</span>`).join('')}</div><p class="placed"><b>Order type:</b> ${fulfillmentType === 'pickup' ? 'Pick Up' : 'Delivery'}<br><b>Placed:</b> ${esc(placed)} · Goa time</p><div class="items"><h2>Your items</h2>${items.map((item)=>`<div><b>${Number(item.quantity||0)}×</b> ${esc(item.name)}${item.portion?` (${esc(item.portion)})`:''}${item.style?` · ${esc(item.style)}`:''}</div>`).join('')}</div>${cancellation}`; };
async function load(){if(!/^[A-Za-z0-9_-]{24,128}$/.test(token)){card.innerHTML='<h1>Order link unavailable</h1><p class="muted">Please use the link from your order confirmation.</p>';return;}try{const response=await fetch(`/api/order-tracking/${encodeURIComponent(token)}`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error||'Order not found.');render(body);}catch(error){card.innerHTML=`<h1>We could not load this order</h1><p class="muted">${esc(error.message)}</p>`;}}
load();window.setInterval(load,15000);
card.addEventListener('click',(event)=>{if(event.target.id==='open-cancel'){document.getElementById('cancel-form').hidden=false;event.target.hidden=true;document.getElementById('cancel-reason').focus();}});
card.addEventListener('submit',async(event)=>{if(event.target.id!=='cancel-form')return;event.preventDefault();const button=event.target.querySelector('button');const reason=document.getElementById('cancel-reason').value.trim();if(reason.length<3){document.getElementById('cancel-reason').focus();return;}button.disabled=true;try{const response=await fetch(`/api/order-tracking/${encodeURIComponent(token)}/cancel`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Unable to cancel this order.');load();}catch(error){button.disabled=false;window.alert(error.message);}});
